name: Database
abbreviation: db
checker: PragmaRX\Health\Checkers\Database
notify: true
column_size: 3
targets:
  - users:
      type: "find_first_model"
      models:
        - "{{ config('auth.providers.users.model') }}"
  - "mysql1":
      type: "raw_query"
      connection: "mysql"
      query: "select * from users limit 1"
      maximum_time: 10
      error_message: "Query took %sms when it should have last at most %sms"